spring:
  application:
    name: lark

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lark?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

# 应用配置
app:
  config:
    # 版本，方便通过接口版本升级
    api-version: v1
    # 跨域，开发阶段可以设置为 * 不限制
    cross-origin: '*'
    # 模型最大重试次数
    max-retry-times: 1

server:
  port: 80

langchain4j:
  open-ai:
    chat-model:
      base-url: 'https://ark.cn-beijing.volces.com/api/v3'
      api-key: 'ec4c495e-e640-476a-b35b-228af0c5b457'
      model-name: 'doubao-seed-1-6-250615'
      log-requests: true
      log-responses: true
