spring:
  application:
    name: lark
  datasource:
    url: jdbc:mysql://localhost:3306/lark
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

milvus:
  uri: http://localhost:19530
  token: root:Milvus

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

# 应用配置
app:
  config:
    # 版本，方便通过接口版本升级
    api-version: v1
    # 跨域，开发阶段可以设置为 * 不限制
    cross-origin: '*'
    # 视觉模型最大重试次数
    vision-max-retry-times: 5
    # 代码模型最大重试次数
    code-max-retry-times: 0
    # 向量检索topK
    vector-topK: 3
    # SSE推送帧率
    sse-fps: 24
    # 向量模型维数
    vector-dimension: 2048

server:
  port: 80

open-ai:
  doubao:
    base-url: 'https://dashscope.aliyuncs.com/compatible-mode/v1'
    api-key: 'sk-69e6710628df43daab681c347712d328'
    model-name: 'deepseek-v3'
    max-tokens: 5000
  doubao-vision:
    base-url: 'https://dashscope.aliyuncs.com/compatible-mode/v1'
    api-key: 'sk-69e6710628df43daab681c347712d328'
    model-name: 'qwen-vl-max-latest'
  doubao-embedding:
    base-url: 'https://ark.cn-beijing.volces.com/api/v3'
    api-key: 'ec4c495e-e640-476a-b35b-228af0c5b457'
    model-name: 'doubao-embedding-large-text-250515'
#  doubao-embedding:
#    base-url: 'https://dashscope.aliyuncs.com/compatible-mode/v1'
#    api-key: 'sk-69e6710628df43daab681c347712d328'
#    model-name: 'text-embedding-v4'
#  doubao-vision:
#    base-url: 'http://localhost:11434'
#    api-key: ''
#    model-name: 'qwen2.5vl:7b-q8_0'
#    log-requests: true
#    log-responses: true


offset:
  xOffset: 0
  yOffset: 0
  xRate: 1
  yRate: 1
#  xRate: 1.25
#  yRate: 0.703125
